targets:
  $default:
    builders:
      hive_generator|hive_generator:
        enabled: true

#builders:
#  color_validation:
#    import: "lib/core/validation/build_color_validator.dart"
#    builder_factories: ["colorValidationBuilder"]
#    build_extensions: {".dart": [".color_validation"]}
#    auto_apply: dependents
#    build_to: cache