// Mocks generated by Mockito 5.4.4 from annotations
// in todo_cleanarc/test/core/services/background_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_cleanarc/core/domain/value_objects/email.dart' as _i12;
import 'package:todo_cleanarc/core/domain/value_objects/password.dart' as _i13;
import 'package:todo_cleanarc/core/domain/value_objects/task_id.dart' as _i8;
import 'package:todo_cleanarc/core/domain/value_objects/user_id.dart' as _i9;
import 'package:todo_cleanarc/core/error/failures.dart' as _i5;
import 'package:todo_cleanarc/core/network/network_info.dart' as _i14;
import 'package:todo_cleanarc/core/utils/pagination_helper.dart' as _i7;
import 'package:todo_cleanarc/feature/auth/domain/entities/user_entity.dart'
    as _i11;
import 'package:todo_cleanarc/feature/auth/domain/repositories/auth_repository.dart'
    as _i10;
import 'package:todo_cleanarc/feature/todo/domain/entities/task_entity.dart'
    as _i6;
import 'package:todo_cleanarc/feature/todo/domain/repositories/task_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskRepository_1 extends _i1.SmartFake
    implements _i3.TaskRepository {
  _FakeTaskRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_2<T> extends _i1.SmartFake implements _i4.Future<T> {
  _FakeFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFailure_3 extends _i1.SmartFake implements _i5.Failure {
  _FakeFailure_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskEntity_4 extends _i1.SmartFake implements _i6.TaskEntity {
  _FakeTaskEntity_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginationHelper_5<T> extends _i1.SmartFake
    implements _i7.PaginationHelper<T> {
  _FakePaginationHelper_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskId_6 extends _i1.SmartFake implements _i8.TaskId {
  _FakeTaskId_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserId_7 extends _i1.SmartFake implements _i9.UserId {
  _FakeUserId_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>> createTask(
          _i6.TaskEntity? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.TaskEntity>(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>> updateTask(
          _i6.TaskEntity? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.TaskEntity>(
          this,
          Invocation.method(
            #updateTask,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteTask(_i8.TaskId? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [taskId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteTask,
            [taskId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity?>> getTaskById(
          _i8.TaskId? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [taskId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity?>>.value(
                _FakeEither_0<_i5.Failure, _i6.TaskEntity?>(
          this,
          Invocation.method(
            #getTaskById,
            [taskId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.PaginationHelper<_i6.TaskEntity>>>
      getTasks({
    _i9.UserId? userId,
    int? page = 1,
    int? limit = 20,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getTasks,
              [],
              {
                #userId: userId,
                #page: page,
                #limit: limit,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i7.PaginationHelper<_i6.TaskEntity>>>.value(
                _FakeEither_0<_i5.Failure,
                    _i7.PaginationHelper<_i6.TaskEntity>>(
              this,
              Invocation.method(
                #getTasks,
                [],
                {
                  #userId: userId,
                  #page: page,
                  #limit: limit,
                },
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i7.PaginationHelper<_i6.TaskEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> syncWithRemote() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWithRemote,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #syncWithRemote,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i10.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.UserEntity>> signInWithEmail({
    required _i12.Email? email,
    required _i13.Password? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i11.UserEntity>>.value(
            _FakeEither_0<_i5.Failure, _i11.UserEntity>(
          this,
          Invocation.method(
            #signInWithEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i11.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.UserEntity>> signUpWithEmail({
    required _i12.Email? email,
    required _i13.Password? password,
    required String? fullName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [],
          {
            #email: email,
            #password: password,
            #fullName: fullName,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i11.UserEntity>>.value(
            _FakeEither_0<_i5.Failure, _i11.UserEntity>(
          this,
          Invocation.method(
            #signUpWithEmail,
            [],
            {
              #email: email,
              #password: password,
              #fullName: fullName,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i11.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.UserEntity?>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i11.UserEntity?>>.value(
                _FakeEither_0<_i5.Failure, _i11.UserEntity?>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i11.UserEntity?>>);

  @override
  _i4.Stream<_i11.UserEntity?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i11.UserEntity?>.empty(),
      ) as _i4.Stream<_i11.UserEntity?>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i14.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}