// Mocks generated by Mockito 5.4.4 from annotations
// in todo_cleanarc/test/core/services/color_resolver_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_cleanarc/core/domain/entities/color_token.dart' as _i5;
import 'package:todo_cleanarc/core/domain/repositories/color_repository.dart'
    as _i3;
import 'package:todo_cleanarc/core/error/failures.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ColorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockColorRepository extends _i1.Mock implements _i3.ColorRepository {
  MockColorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i7.Failure, _i5.ColorToken?>> getColorToken(
    String? tokenName,
    _i6.ThemeMode? mode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getColorToken,
          [
            tokenName,
            mode,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i7.Failure, _i5.ColorToken?>>.value(
            _FakeEither_0<_i7.Failure, _i5.ColorToken?>(
          this,
          Invocation.method(
            #getColorToken,
            [
              tokenName,
              mode,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, _i5.ColorToken?>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, Map<String, _i5.ColorToken>>>
      getColorTokens(_i6.ThemeMode? mode) => (super.noSuchMethod(
            Invocation.method(
              #getColorTokens,
              [mode],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i7.Failure, Map<String, _i5.ColorToken>>>.value(
                _FakeEither_0<_i7.Failure, Map<String, _i5.ColorToken>>(
              this,
              Invocation.method(
                #getColorTokens,
                [mode],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i7.Failure, Map<String, _i5.ColorToken>>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, bool>> checkAccessibilityCompliance(
    _i5.ColorToken? foreground,
    _i5.ColorToken? background,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAccessibilityCompliance,
          [
            foreground,
            background,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i7.Failure, bool>>.value(
            _FakeEither_0<_i7.Failure, bool>(
          this,
          Invocation.method(
            #checkAccessibilityCompliance,
            [
              foreground,
              background,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, void>> validateRequiredTokens(
    Map<String, _i5.ColorToken>? tokens,
    List<String>? requiredTokens,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateRequiredTokens,
          [
            tokens,
            requiredTokens,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #validateRequiredTokens,
            [
              tokens,
              requiredTokens,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, void>> validateTokenNaming(
          Map<String, _i5.ColorToken>? tokens) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateTokenNaming,
          [tokens],
        ),
        returnValue: _i4.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #validateTokenNaming,
            [tokens],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, void>> validateTokenDependencies(
          Map<String, _i5.ColorToken>? tokens) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateTokenDependencies,
          [tokens],
        ),
        returnValue: _i4.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #validateTokenDependencies,
            [tokens],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, void>>);
}