// Mocks generated by Mockito 5.4.4 from annotations
// in todo_cleanarc/test/core/services/theme_provider_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_cleanarc/core/domain/entities/app_theme_config.dart'
    as _i5;
import 'package:todo_cleanarc/core/domain/entities/theme_state.dart' as _i7;
import 'package:todo_cleanarc/core/domain/repositories/theme_repository.dart'
    as _i3;
import 'package:todo_cleanarc/core/error/failures.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ThemeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeRepository extends _i1.Mock implements _i3.ThemeRepository {
  MockThemeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i8.Failure, _i5.AppThemeConfig>> getCurrentTheme() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentTheme,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i8.Failure, _i5.AppThemeConfig>>.value(
                _FakeEither_0<_i8.Failure, _i5.AppThemeConfig>(
          this,
          Invocation.method(
            #getCurrentTheme,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, _i5.AppThemeConfig>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> saveTheme(
          _i5.AppThemeConfig? theme) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTheme,
          [theme],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #saveTheme,
            [theme],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, List<_i5.AppThemeConfig>>>
      getAvailableThemes() => (super.noSuchMethod(
            Invocation.method(
              #getAvailableThemes,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i8.Failure, List<_i5.AppThemeConfig>>>.value(
                _FakeEither_0<_i8.Failure, List<_i5.AppThemeConfig>>(
              this,
              Invocation.method(
                #getAvailableThemes,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i8.Failure, List<_i5.AppThemeConfig>>>);

  @override
  _i4.Stream<_i6.ThemeMode> watchSystemTheme() => (super.noSuchMethod(
        Invocation.method(
          #watchSystemTheme,
          [],
        ),
        returnValue: _i4.Stream<_i6.ThemeMode>.empty(),
      ) as _i4.Stream<_i6.ThemeMode>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, _i7.ThemeState>> getThemeState() =>
      (super.noSuchMethod(
        Invocation.method(
          #getThemeState,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, _i7.ThemeState>>.value(
            _FakeEither_0<_i8.Failure, _i7.ThemeState>(
          this,
          Invocation.method(
            #getThemeState,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, _i7.ThemeState>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, _i5.AppThemeConfig>> getDefaultTheme() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultTheme,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i8.Failure, _i5.AppThemeConfig>>.value(
                _FakeEither_0<_i8.Failure, _i5.AppThemeConfig>(
          this,
          Invocation.method(
            #getDefaultTheme,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, _i5.AppThemeConfig>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> validateTheme(
          _i5.AppThemeConfig? theme) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateTheme,
          [theme],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #validateTheme,
            [theme],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> setSystemThemeEnabled(
          bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSystemThemeEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #setSystemThemeEnabled,
            [enabled],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> addCustomTheme(
          _i5.AppThemeConfig? theme) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCustomTheme,
          [theme],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #addCustomTheme,
            [theme],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);
}