// Mocks generated by Mockito 5.4.4 from annotations
// in todo_cleanarc/test/feature/todo/presentation/bloc/task_form_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_cleanarc/core/domain/value_objects/task_id.dart' as _i10;
import 'package:todo_cleanarc/core/error/failures.dart' as _i6;
import 'package:todo_cleanarc/feature/todo/domain/entities/task_entity.dart'
    as _i7;
import 'package:todo_cleanarc/feature/todo/domain/repositories/task_repository.dart'
    as _i2;
import 'package:todo_cleanarc/feature/todo/domain/usecases/create_task_usecase.dart'
    as _i4;
import 'package:todo_cleanarc/feature/todo/domain/usecases/get_task_by_id_usecase.dart'
    as _i9;
import 'package:todo_cleanarc/feature/todo/domain/usecases/update_task_usecase.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskRepository_0 extends _i1.SmartFake
    implements _i2.TaskRepository {
  _FakeTaskRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CreateTaskUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTaskUseCase extends _i1.Mock implements _i4.CreateTaskUseCase {
  MockCreateTaskUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTaskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TaskRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i7.TaskEntity? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [task],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [task],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [UpdateTaskUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTaskUseCase extends _i1.Mock implements _i8.UpdateTaskUseCase {
  MockUpdateTaskUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTaskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TaskRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i7.TaskEntity? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [task],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [task],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetTaskByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTaskByIdUseCase extends _i1.Mock
    implements _i9.GetTaskByIdUseCase {
  MockGetTaskByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTaskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TaskRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.TaskEntity?>> call(
          _i10.TaskId? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [taskId],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.TaskEntity?>>.value(
            _FakeEither_1<_i6.Failure, _i7.TaskEntity?>(
          this,
          Invocation.method(
            #call,
            [taskId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.TaskEntity?>>);
}
