// Mocks generated by Mockito 5.4.4 from annotations
// in todo_cleanarc/test/integration/task_repository_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_cleanarc/core/network/network_info.dart' as _i7;
import 'package:todo_cleanarc/core/utils/pagination_helper.dart' as _i2;
import 'package:todo_cleanarc/feature/todo/data/datasources/hive_task_datasource.dart'
    as _i4;
import 'package:todo_cleanarc/feature/todo/data/datasources/supabase_task_datasource.dart'
    as _i6;
import 'package:todo_cleanarc/feature/todo/data/models/task_model.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedResult_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResult<T> {
  _FakePaginatedResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskModel_1 extends _i1.SmartFake implements _i3.TaskModel {
  _FakeTaskModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HiveTaskDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveTaskDataSource extends _i1.Mock
    implements _i4.HiveTaskDataSource {
  MockHiveTaskDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.TaskModel>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i5.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i5.Future<List<_i3.TaskModel>>);

  @override
  _i5.Future<_i2.PaginatedResult<_i3.TaskModel>> getTasksPaginated({
    int? page = 0,
    int? pageSize = 20,
    String? searchQuery,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksPaginated,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #searchQuery: searchQuery,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i5.Future<_i2.PaginatedResult<_i3.TaskModel>>.value(
            _FakePaginatedResult_0<_i3.TaskModel>(
          this,
          Invocation.method(
            #getTasksPaginated,
            [],
            {
              #page: page,
              #pageSize: pageSize,
              #searchQuery: searchQuery,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i5.Future<_i2.PaginatedResult<_i3.TaskModel>>);

  @override
  _i5.Future<_i3.TaskModel?> getTaskById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [id],
        ),
        returnValue: _i5.Future<_i3.TaskModel?>.value(),
      ) as _i5.Future<_i3.TaskModel?>);

  @override
  _i5.Future<void> createTask(_i3.TaskModel? task) => (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTask(_i3.TaskModel? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.TaskModel>> getTasksByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i5.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i5.Future<List<_i3.TaskModel>>);

  @override
  _i5.Future<List<_i3.TaskModel>> searchTasks(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTasks,
          [query],
        ),
        returnValue: _i5.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i5.Future<List<_i3.TaskModel>>);

  @override
  _i5.Future<List<_i3.TaskModel>> getTasksNeedingSync() => (super.noSuchMethod(
        Invocation.method(
          #getTasksNeedingSync,
          [],
        ),
        returnValue: _i5.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i5.Future<List<_i3.TaskModel>>);

  @override
  _i5.Future<void> markTaskForSync(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markTaskForSync,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markTaskSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markTaskSynced,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchCreateTasks(List<_i3.TaskModel>? tasks) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreateTasks,
          [tasks],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchUpdateTasks(List<_i3.TaskModel>? tasks) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateTasks,
          [tasks],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchDeleteTasks(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDeleteTasks,
          [ids],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> hasConflict(_i3.TaskModel? task) => (super.noSuchMethod(
        Invocation.method(
          #hasConflict,
          [task],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> clearAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #clearAllTasks,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getTaskCount() => (super.noSuchMethod(
        Invocation.method(
          #getTaskCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> optimizeStorage() => (super.noSuchMethod(
        Invocation.method(
          #optimizeStorage,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SupabaseTaskDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseTaskDataSource extends _i1.Mock
    implements _i6.SupabaseTaskDataSource {
  MockSupabaseTaskDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.TaskModel>> getAllTasks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [userId],
        ),
        returnValue: _i5.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i5.Future<List<_i3.TaskModel>>);

  @override
  _i5.Future<_i2.PaginatedResult<_i3.TaskModel>> getTasksPaginated(
    String? userId, {
    int? page = 0,
    int? pageSize = 20,
    String? searchQuery,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksPaginated,
          [userId],
          {
            #page: page,
            #pageSize: pageSize,
            #searchQuery: searchQuery,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i5.Future<_i2.PaginatedResult<_i3.TaskModel>>.value(
            _FakePaginatedResult_0<_i3.TaskModel>(
          this,
          Invocation.method(
            #getTasksPaginated,
            [userId],
            {
              #page: page,
              #pageSize: pageSize,
              #searchQuery: searchQuery,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i5.Future<_i2.PaginatedResult<_i3.TaskModel>>);

  @override
  _i5.Future<_i3.TaskModel?> getTaskById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [id],
        ),
        returnValue: _i5.Future<_i3.TaskModel?>.value(),
      ) as _i5.Future<_i3.TaskModel?>);

  @override
  _i5.Future<_i3.TaskModel> createTask(_i3.TaskModel? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i5.Future<_i3.TaskModel>.value(_FakeTaskModel_1(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i5.Future<_i3.TaskModel>);

  @override
  _i5.Future<_i3.TaskModel> updateTask(_i3.TaskModel? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i5.Future<_i3.TaskModel>.value(_FakeTaskModel_1(
          this,
          Invocation.method(
            #updateTask,
            [task],
          ),
        )),
      ) as _i5.Future<_i3.TaskModel>);

  @override
  _i5.Future<void> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.TaskModel>> getTasksByDateRange(
    String? userId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByDateRange,
          [
            userId,
            start,
            end,
          ],
        ),
        returnValue: _i5.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i5.Future<List<_i3.TaskModel>>);

  @override
  _i5.Future<List<_i3.TaskModel>> searchTasks(
    String? userId,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTasks,
          [
            userId,
            query,
          ],
        ),
        returnValue: _i5.Future<List<_i3.TaskModel>>.value(<_i3.TaskModel>[]),
      ) as _i5.Future<List<_i3.TaskModel>>);

  @override
  _i5.Future<void> batchCreateTasks(List<_i3.TaskModel>? tasks) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCreateTasks,
          [tasks],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchUpdateTasks(List<_i3.TaskModel>? tasks) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateTasks,
          [tasks],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchDeleteTasks(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #batchDeleteTasks,
          [ids],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<List<_i3.TaskModel>> watchTasks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTasks,
          [userId],
        ),
        returnValue: _i5.Stream<List<_i3.TaskModel>>.empty(),
      ) as _i5.Stream<List<_i3.TaskModel>>);

  @override
  _i5.Future<void> syncTasks(
    List<_i3.TaskModel>? localTasks,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncTasks,
          [
            localTasks,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getTaskCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getTaskCount,
          [userId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
